### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by fsantanna** [micahkendall/freechains-lua#2]
- How to use the API
- Some simple example that makes something real.

**Comment by fsantanna** [comment]
My suggestion is to have a single page with all docs.

Also, it should be possible to copy & paste the commands to install the library at once, e.g.:

```
- Clone this repository:
  git clone ...
- Change directory to library sources:
  cd ...
- Edit sample file `ex.lua`:
  vi ex.lua
- etc
```

You can link to freechains install docs, don't need to repeat yourself.

**Comment by fsantanna** [comment]
I didn't understand the API.
It needs more clarifications.
What is this `string ...`?

Could you add a full simple example that one can copy & paste?

**Comment by micahkendall** [comment]
Revised api - will be redoing docs, then applying these updates.
